<?php
include ('config.php');
include ('functions.php');
$ID = $_SESSION['BranchID'];
$res='SELECT branches.BranchID, product.*
						FROM `branches`
						INNER JOIN product ON branches.BranchID='.$ID.' AND branches.BranchID = product.BranchID AND product.status= "active" ORDER BY product_name ASC' or die(mysqli_errno());
require('fpdf.php');

date_default_timezone_set('Asia/Manila');
$sql = "UPDATE branches SET LastGenerated=CURDATE() WHERE BranchID='".$ID."'";
$conn->query($sql);

class PDF extends FPDF
{
// Page header
function Header()
{
	$branch = $_SESSION['BranchName'];
	date_default_timezone_set('Asia/Manila');
	$date=date('M d, Y');
	$title = $branch." Branch - ".$date;

	$width_cell=array(40,40,30,40,190);
	$this->SetFillColor(255,178,102); // Background color of header 
	$this->SetTextColor(255,178,102);
    // Logo
	$this->Image('logo.png',40,5,30);
	$this->SetFont('Arial','B',20);
	$this->Text(75, 17, 'Fae Fae Lechon Manok,');
	$this->Text(74, 27, 'Crispy Liempo and Sisig');
	// Line break
	$this->Ln(25);
	$this->SetFont('Arial','B',10);
	$this->SetTextColor(0,0,0);
	$this->Cell($width_cell[4],10,$title,1,1,'C',false);
	$this->Cell($width_cell[1],10,'Product Name',1,0,'C',true); // First header column 
	$this->Cell($width_cell[2],10,'Unit',1,0,'C',true); // First header column 
	$this->Cell($width_cell[0],10,'Starting Quantity',1,0,'C',true); // Second header column
	$this->Cell($width_cell[0],10,'Quantity Consumed',1,0,'C',true); // Third header column 
	$this->Cell($width_cell[0],10,'Quantity Needed',1,0,'C',true); // Fourth header column
	$this->Ln();

}

// Page footer
function Footer()
{
	$user = $_SESSION['name'];
	date_default_timezone_set('Asia/Manila');
	$date=date('M d, Y  H:i:s');
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
	$this->SetAutoPageBreak(false);
    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
	$this->Ln(4);
	$this->Cell(0,10,'Generated by: '.$user.' - '.$date.'',0,0,'C');
}
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial','B',10);
$branch = $_SESSION['BranchName'];
date_default_timezone_set('Asia/Manila');
$date=date('M d, Y');
$title = $branch." Branch - ".$date;

$width_cell=array(40,40,30,40,190);
$pdf->SetFont('Arial','B',10);
$pdf->SetFillColor(255,178,102); // Background color of header 
// Header starts /// 

//// header ends ///////

$pdf->SetFont('Arial','',10);
$pdf->SetFillColor(255,213,213); // Background color of header 
$fill=false; // to give alternate background fill color to rows 

/// each record is one row  ///
foreach ($dbo->query($res) as $row) {
$pdf->Cell($width_cell[1],6,$row['product_name'],1,0,'C');
$pdf->Cell($width_cell[2],6,$row['unit'],1,0,'C');
$pdf->Cell($width_cell[0],6,$row['start_amt'],1,0,'C');
$pdf->Cell($width_cell[0],6,$row['start_amt']-$row['quantity'],1,0,'C');
$pdf->Cell($width_cell[0],6,$row['amt_need'],1,0,'C');
// !$fill = !$fill; // to give alternate background fill  color to rows
$pdf->Ln();
}

$name='.pdf';
$filename=$branch." Branch - ".$date.$name;

$pdf->Output('D',$filename)
?>